package godocx

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestEnglishFixtures checks the structural shape of every generated English
// fixture. Regenerate the fixtures with: go run ./testdata/gen
func TestEnglishFixtures(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name       string
		filename   string
		bodyBlocks int
		headers    int
		footers    int
		footnotes  int
		endnotes   int
		wantText   []string
	}{
		{
			name:       "simple",
			filename:   "simple.docx",
			bodyBlocks: 11,
			wantText: []string{
				"Quarterly Service Report",
				"Region\tContact\tStatus",
				"Scope of Work",
				"project documentation",
			},
		},
		{
			name:       "flat tables",
			filename:   "tables.docx",
			bodyBlocks: 5,
			wantText: []string{
				"Item\tQuantity\tUnit price\tTotal",
				"Annual licence\t12\tEUR 240.00\tEUR 2,880.00",
			},
		},
		{
			name:       "merged tables",
			filename:   "tables-merged.docx",
			bodyBlocks: 3,
			wantText: []string{
				// A vMerge continuation inherits the origin cell text.
				"Phase 1\tEnvironment handover\t2026-02-02",
				"Phase 2\tAcceptance testing\t2026-03-28",
				// A gridSpan cell renders once and leaves covered columns empty.
				"Total duration: 11 weeks\t\tConfirmed",
			},
		},
		{
			name:       "nested tables",
			filename:   "nested-tables.docx",
			bodyBlocks: 3,
			wantText: []string{
				"Cost Breakdown",
				"Setup fee",
				"Training day",
			},
		},
		{
			name:       "nested lists",
			filename:   "lists-nested.docx",
			bodyBlocks: 18,
			wantText: []string{
				"1. Prepare the test environment.",
				"  a. Restore the anonymised data set.",
				"    i. Confirm read-only access for auditors.",
				"2. Run the acceptance test suite.",
				"- Functional requirements",
				"  - Search and filtering",
				// numId 3 carries a startOverride of five.
				"5. Continued item after a restart override.",
				"6. Second item after the restart override.",
			},
		},
		{
			name:       "images",
			filename:   "images.docx",
			bodyBlocks: 8,
			wantText: []string{
				"Embedded Images",
				"[image: word/media/logo.png]",
				"[image: word/media/badge.svg]",
			},
		},
		{
			name:       "unicode and whitespace",
			filename:   "unicode-whitespace.docx",
			bodyBlocks: 7,
			wantText: []string{
				"Ångström Systems Ltd.",
				"José Almeida, Zoë Bjärk, François Muller, Andrzej Wójcik",
				"年度报告",
				// Run whitespace survives xml:space="preserve".
				"Leading and trailing spaces  are preserved across  adjacent runs.",
			},
		},
		{
			name:       "headers and footers",
			filename:   "headers-footers.docx",
			bodyBlocks: 3,
			headers:    2,
			footers:    1,
			wantText: []string{
				"Document With Headers and Footers",
			},
		},
		{
			name:       "footnotes and endnotes",
			filename:   "footnotes-endnotes.docx",
			bodyBlocks: 5,
			footnotes:  3,
			endnotes:   1,
			wantText: []string{
				"[footnote: 2]",
				"[footnote: 3]",
				"[endnote: 2]",
			},
		},
		{
			name:       "content controls",
			filename:   "sdt-content-controls.docx",
			bodyBlocks: 8,
			wantText: []string{
				"Northwind Services Ltd.",
				"Supplier Declaration",
				"Jordan Ellis, Managing Director",
			},
		},
		{
			name:       "fields and alternate content",
			filename:   "fields-alternate-content.docx",
			bodyBlocks: 7,
			wantText: []string{
				"Document reference NS-2026-0147 is generated by a complex field.",
				"A hyperlink field renders its display value: tender detail.",
				"Signature date: 7 September 2026.",
				"Nested fields keep only the outer display value: first page.",
				"Modern rendering: the choice branch is preferred.",
				"Run-level alternate content: choice run.",
			},
		},
		{
			name:       "service agreement",
			filename:   "service-agreement-en.docx",
			bodyBlocks: 40,
			headers:    2,
			footers:    1,
			footnotes:  3,
			wantText: []string{
				"Service Agreement for the Reporting Platform",
				"Harbour City Council",
				"1. Implementation services",
				"Critical\t1 hour\t8 business hours",
				"Implementation\t2\t1,200.00\t2,400.00",
			},
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()

			doc, err := Open(filepath.Join("testdata", tc.filename))
			if err != nil {
				t.Fatalf("Open() error = %v", err)
			}

			if len(doc.Body) != tc.bodyBlocks {
				t.Errorf("len(Body) = %d, want %d", len(doc.Body), tc.bodyBlocks)
			}
			if len(doc.Headers) != tc.headers {
				t.Errorf("len(Headers) = %d, want %d", len(doc.Headers), tc.headers)
			}
			if len(doc.Footers) != tc.footers {
				t.Errorf("len(Footers) = %d, want %d", len(doc.Footers), tc.footers)
			}
			if len(doc.Footnotes) != tc.footnotes {
				t.Errorf("len(Footnotes) = %d, want %d", len(doc.Footnotes), tc.footnotes)
			}
			if len(doc.Endnotes) != tc.endnotes {
				t.Errorf("len(Endnotes) = %d, want %d", len(doc.Endnotes), tc.endnotes)
			}

			text := doc.ToText()
			for _, want := range tc.wantText {
				if !strings.Contains(text, want) {
					t.Errorf("ToText() does not contain %q", want)
				}
			}
			if doc.ToMarkdown() == "" {
				t.Error("ToMarkdown() is empty")
			}
			if len(doc.Chunks()) == 0 {
				t.Error("Chunks() is empty")
			}
		})
	}
}

// TestEnglishFixtureFieldInstructionsHidden checks that field instructions never
// reach the rendered output, only their cached display values.
func TestEnglishFixtureFieldInstructionsHidden(t *testing.T) {
	t.Parallel()

	doc, err := Open(filepath.Join("testdata", "fields-alternate-content.docx"))
	if err != nil {
		t.Fatalf("Open() error = %v", err)
	}

	text := doc.ToText()
	for _, unwanted := range []string{"HYPERLINK", "NUMPAGES", "MMMM", "_Ref12345", "Legacy rendering", "fallback run"} {
		if strings.Contains(text, unwanted) {
			t.Errorf("ToText() unexpectedly contains %q", unwanted)
		}
	}
}

// TestEnglishFixtureImages checks lazy image loading, part-scoped image IDs, and
// content-type detection for every embedded format.
//
// Every fixture is loaded through both entry points. Open must produce loadable
// images too: it used to close the underlying file before lazy image loading
// could read the media parts.
func TestEnglishFixtureImages(t *testing.T) {
	t.Parallel()

	loaders := []struct {
		name string
		open func(testing.TB, string) *Document
	}{
		{name: "Open", open: openFixtureFromDisk},
		{name: "OpenReader", open: openFixtureFromMemory},
	}

	tests := []struct {
		name     string
		filename string
		want     []Image
	}{
		{
			name:     "body images",
			filename: "images.docx",
			want: []Image{
				{ID: "word/document.xml#rId1", ContentType: "image/png", AltText: "Company logo in PNG format"},
				{ID: "word/document.xml#rId2", ContentType: "image/jpeg", AltText: "Office photograph in JPEG format"},
				{ID: "word/document.xml#rId3", ContentType: "image/gif", AltText: "Status icon in GIF format"},
				{ID: "word/document.xml#rId4", ContentType: "image/svg+xml", AltText: "Certification badge in SVG format"},
			},
		},
		{
			name:     "header image",
			filename: "headers-footers.docx",
			want: []Image{
				{ID: "word/header2.xml#rId1", ContentType: "image/png", AltText: "Supplier logo in the first-page header"},
			},
		},
		{
			name:     "body and header images share a relationship id",
			filename: "service-agreement-en.docx",
			want: []Image{
				{ID: "word/document.xml#rId7", ContentType: "image/png", AltText: "Architecture overview of the reporting platform"},
				{ID: "word/header2.xml#rId1", ContentType: "image/png", AltText: "Northwind Services logo"},
			},
		},
	}

	for _, loader := range loaders {
		for _, tc := range tests {
			t.Run(loader.name+"/"+tc.name, func(t *testing.T) {
				t.Parallel()

				doc := loader.open(t, tc.filename)

				images, err := doc.AllImages()
				if err != nil {
					t.Fatalf("AllImages() error = %v", err)
				}
				if len(images) != len(tc.want) {
					t.Fatalf("len(AllImages()) = %d, want %d", len(images), len(tc.want))
				}

				for i, want := range tc.want {
					got := images[i]
					if got.ID != want.ID {
						t.Errorf("images[%d].ID = %q, want %q", i, got.ID, want.ID)
					}
					if got.ContentType != want.ContentType {
						t.Errorf("images[%d].ContentType = %q, want %q", i, got.ContentType, want.ContentType)
					}
					if got.AltText != want.AltText {
						t.Errorf("images[%d].AltText = %q, want %q", i, got.AltText, want.AltText)
					}
					if len(got.Bytes) == 0 {
						t.Errorf("images[%d].Bytes is empty", i)
					}
				}

				// Single-image lookup must resolve the same bytes by ID.
				for _, want := range tc.want {
					image, err := doc.Image(want.ID)
					if err != nil {
						t.Errorf("Image(%q) error = %v", want.ID, err)
						continue
					}
					if len(image.Bytes) == 0 {
						t.Errorf("Image(%q).Bytes is empty", want.ID)
					}
				}
			})
		}
	}
}

func openFixtureFromDisk(tb testing.TB, filename string) *Document {
	tb.Helper()

	doc, err := Open(filepath.Join("testdata", filename))
	if err != nil {
		tb.Fatalf("Open() error = %v", err)
	}
	return doc
}

func openFixtureFromMemory(tb testing.TB, filename string) *Document {
	tb.Helper()

	data, err := os.ReadFile(filepath.Join("testdata", filename))
	if err != nil {
		tb.Fatalf("ReadFile() error = %v", err)
	}
	doc, err := OpenReader(bytes.NewReader(data), int64(len(data)))
	if err != nil {
		tb.Fatalf("OpenReader() error = %v", err)
	}
	return doc
}

// TestEnglishFixtureMalformed checks that a truncated archive is rejected
// instead of panicking.
func TestEnglishFixtureMalformed(t *testing.T) {
	t.Parallel()

	if _, err := Open(filepath.Join("testdata", "malformed-truncated.docx")); err == nil {
		t.Fatal("Open() error = nil, want an error for a truncated archive")
	}
}

// TestOpenErrorPaths checks that Open reports an error instead of panicking for
// inputs that are not readable DOCX files.
func TestOpenErrorPaths(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		path string
	}{
		{name: "missing file", path: filepath.Join("testdata", "does-not-exist.docx")},
		{name: "directory", path: "testdata"},
		{name: "not an archive", path: filepath.Join("testdata", "README.md")},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()

			if _, err := Open(tc.path); err == nil {
				t.Fatalf("Open(%q) error = nil, want an error", tc.path)
			}
		})
	}
}
